spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_info?useSSL=false
    username: root
    password: HANXUEXUN095827
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
